version: '3.7'
services:

  postgres-server:    # The Postgres Database Service
    image: postgres:14
    hostname: postgres-server
    restart: always
    networks:
      - zbx_net
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
      # PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - /zabbix-pgsql:/var/lib/postgresql/data/pgdata:rw

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    hostname: zabbix-server
    restart: always
    networks:
      - zbx_net
    ports:
      - 10051:10051
    environment:   # The Postgres database value variable
      DB_SERVER_HOST: postgres-server
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    # volumes:  # Volumes for scripts and related files you can add
    #   - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - /zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix-data/export:/var/lib/zabbix/export:rw
      - /zabbix-data/modules:/var/lib/zabbix/modules:ro
      - /zabbix-data/enc:/var/lib/zabbix/enc:ro
      - /zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix-data/mibs:/var/lib/zabbix/mibs:ro
      - /zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw

  zabbix-web:    # The main Zabbix web UI or interface 
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    restart: always
    networks:
      - zbx_net
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
      DB_SERVER_HOST: postgres-server
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8080:8080

  # zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
  #   image: zabbix/zabbix-agent:ubuntu-6.4-latest
  #   privileged: true   #access mode for allowing resource access
  #   network_mode: "host"
  #   restart: unless-stopped
  #   environment:
  #     - ZBX_SERVER_HOST=127.0.0.1 #the IP/Dns of Zabbix server

  # adminer:  #Optional for accessing databases
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # grafana-xxl:  #optional more functional and creative UI 
  #   image: monitoringartist/grafana-xxl:latest
  #   ports:
  #    - 3000:3000

networks:
  zbx_net: