version: '3.5'
services:
  postgres-server:
    image: postgres:14
    hostname: postgres-server
    restart: always
    networks:
      - zbx_net
    # command:
    #   - mysqld
    #   - --character-set-server=utf8
    #   - --collation-server=utf8_bin
    #   - --default-authentication-plugin=mysql_native_password
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_DB=zabbixdb
      - POSTGRES_PASSWORD=zabbix
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    volumes:
      - /zabbix-pgsql:/var/lib/mysql:rw

  zabbix-server-mysql:
    # image: zabbix/zabbix-server-mysql:alpine-latest
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    hostname: zabbix-server-pgsql
    networks:
      - zbx_net
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - /zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix-data/export:/var/lib/zabbix/export:rw
      - /zabbix-data/modules:/var/lib/zabbix/modules:ro
      - /zabbix-data/enc:/var/lib/zabbix/enc:ro
      - /zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix-data/mibs:/var/lib/zabbix/mibs:ro
      - /zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - DB_SERVER_HOST=postgres-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - postgres-server

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    networks:
      - zbx_net
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix-nginx/nginx:/etc/ssl/nginx:ro
      - /zabbix-nginx/modules/:/usr/share/zabbix/modules/:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=postgres-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - postgres-server
      - zabbix-server-mysql

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.4-latest
    networks:
      - zbx_net
    ports:
      - 10052:10052

  # zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
  #   image: zabbix/zabbix-agent:ubuntu-6.2-latest
  #   privileged: true   #access mode for allowing resource access
  #   network_mode: "host"
  #   ports:
  #     - 10050:10050
  #   restart: unless-stopped
  #   environment:
  #     - ZBX_SERVER_HOST=127.0.0.1 #the IP/Dns of Zabbix server

networks:
  zbx_net:
    # driver: bridge